name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'Android/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'Android/**'

jobs:
  build_apk:
    name: Build Android APK
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Android/src
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v3
      
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      
      - name: Decode Keystore
        run: |
          echo "$KEYSTORE_B64" | base64 -d > gallery-release.keystore
        env:
          KEYSTORE_B64: MIIK2gIBAzCCCoQGCSqGSIb3DQEHAaCCCnUEggpxMIIKbTCCBcQGCSqGSIb3DQEHAaCCBbUEggWxMIIFrTCCBakGCyqGSIb3DQEMCgECoIIFQDCCBTwwZgYJKoZIhvcNAQUNMFkwOAYJKoZIhvcNAQUMMCsEFIAbIWKhR0HZ7ZVemJoibHrDppZoAgInEAIBIDAMBggqhkiG9w0CCQUAMB0GCWCGSAFlAwQBKgQQXoYKmUHDCvpe8d7HITucqgSCBNCubbLmThrTKHZH4ifw4BzPN+8XvSV4BdlLdoaw3Ou5NDx34Qk8fr0d9qFIEUOlcP4MmPs/g/q0JJtxZ62HzBVr5QzvQKPcKfEOc5wfFbMxRpPhj47mcqSOGeiFSfGmMMxZRwWAQypTF7fCWldaH7363JFaE4wTGxnHTUPuwGAPbBu4gW9AqI+nFLHbFOOsDWntwiIqsqTr6L3oEb13bN8kCcR+hWiWcVerLQJROH0mRNuYHhWTjbvdilGwNavZVg3maaAVPvpCO/v0JJcWKxRPe9wW8pwrIqVKbAVbPqyKkf+l6Zsjked3T7OVKX2xNeaRcqaz+3TGv2uFojFR2ihCwK3223X/tLX2BaTBV/emhRJwFwZYhWYjbZVxQl1KXHZlHl3LkKw1dXt2BsJYUHn4nDfnW7kB5m5DrtLZYmpUFH1sqESpTQ0JBFcWFgD1Ms0QFWLOenv0ulDAIB4mIQjCfc6TRph1oXuqjoYzUpOTGbxUQU58zfrW8SlP0fAMJK+u760ad7dWaN2x74NTcbrALEs3MSmaWAueaCu1phHKEDbeW5L/fozueDzTby9VU1YbwPrl3SmHkic6IZdCsDQ4CJWHeSB/FbSgQ8NYKSbr9HXhMEuOOqMDtqrrptYqOrP0doqr07nWU3/BoWj3kIxU7L8+87/jabRCbQYlhjMYygGMl8uMD0HGm3O3xjh7PeyKXsHPS1dZuqQb3BMTjhLhZ8HtbY01QGZy+eczaNhy4Ea4899Qp90KA5tv7enNAvCzYiZOnlIR0QVseZfj3vLL5kY/NAKrHSoSFE2hmcJFjW81hlUYQzGWC4yobBPd/Ku4xiHYZg8M8e/8zBYEfXR2IR7OCW8PUtTGUgVFaDy1u1smjsHt3QHbgVEmvYNP5H+VQFhEH2tWHXD+EFf1/95Dp3aOAxzjAjKa6RbmlzYMvG7wOnVBH/ZuYL6T1y6p9yoHi7/6Yf2Rbfr+zSxQWbGlo9QHnOyHjVLdyoPCAclrOUai5S3WeNDtYGtGjUX5pOXrSLyEijxem7YxAv4ZlaDjGU2TdYyv8lXjbjIOng4iUB8EtjgOKgqvDaf0+0Jz/Pco2yCT2jxXFnmLphzlZxVa1PAAc3er8H/cJijio2hUFE7BUOL7VCR/aP4BBy1Lcjjji1z1fIFYtAFT9Es/DYZGLOC0qsuv28Zj2/ttkbob/TbXoEKbUHTraizb8t0kC+PEd8B8nfGoNJA3B4azz3PQ+7lfSgQcbYBxvNqBN6hBR0iOZQAOPPvGhuHCI2zGzKKbFrRFq5DgD2zkvJYlFZoB0mPOxEeo4RlGkugyMYfZcSLaEEGJXksHSS3Ntmx73dBfSMnwJF44SGiN+wiYemFOR2+SZifXOpqThn90nu0d/J+OGsahSk+a048v5Uc3f7PA+JIw12pDJjeb+xzlQvRnDaGAJ//pYzERvr9bHWU+096BfhO6PB7bq7yayD1a6zg71twtvW4WFcAYeLiD1kfGobtmeiwPte3Uwy/vBhH7CcGEODVvZlq9LhSZTfEfdiLGTbmbH3/X1vuMuXbBdwXFD0i/1uG6+/F0TNsETaT9NOL4kx/bCvq1Yjy9XS81Q9tC9Zuv91Oop8Gl95HF1+Nmc4re/U4KAS/gjMdFbOaNgzFWMDEGCSqGSIb3DQEJFDEkHiIAYQBuAGQAcgBvAGkAZAByAGUAbABlAGEAcwBlAGsAZQB5MCEGCSqGSIb3DQEJFTEUBBJUaW1lIDE3NzU0NzExMjU1ODAwggShBgkqhkiG9w0BBwagggSSMIIEjgIBADCCBIcGCSqGSIb3DQEHATBmBgkqhkiG9w0BBQ0wWTA4BgkqhkiG9w0BBQwwKwQUYwzUpL1T6qaDvIn9S99qlCN+TDYCAicQAgEgMAwGCCqGSIb3DQIJBQAwHQYJYIZIAWUDBAEqBBBOErm7afeXiW3idTF7+zcegIIEEC0I0uTfBWsTXLxQauJHdNaQE5iJUypaW3G4g07K6mp4Nbl6JtqHlXE3Q9jzdcU51LOMFYl44k70/70RJz32eZyLAPbqCFTjYAESI1y1ks5IMt9x1lUGApsBvdcKFEJm6DuacAfHWBtwNZkoaZaRyUzugG3LtViBoDGVDOlKYOAY6QIMfYwaXxRpV49iKNu5gJPkaK2r7CtIAT8S39XapCHKv+ClYMUdv9SSz2NoBp3LSpbVRwpRWYYsbE1yIP5gDlAkcStyGSPns48vzaaSs0VAn5i40sJ5bs/a6zq7UN5vnZpzCOx9MLRVXqwbJrMvRVh1xX+pj6hnFHybyie7yNoXyCibPvLa2oe4PFlU6sATseiowOwlTZ1AOHHipHlqulPAGWigtmrci9EpUGzE8JSYeMY7PJAzRssgrz+IbzPoqFA6yDFmfxRYUOepOMKTqY1/N0wWz7HNN8K3eg6m3doDogNGwPx6/tkFE62qn3XUHjySVZBafM9KxMpx9nl4xB5Lj81QAj+g1tbnHQtljdPGJCUqg2RwAgimoEtHExursU2eATU7NwnK7R4VLnhCU1enS1cNLbR31Sh5C3KTfN+1u6q3pUqki1fES6Y22O3ubnaG/SDitf1ZzKd1GzUJziIwlS/w7VgatGJg2p6lcKnA3rVNBVu3uJr0T23Gm49axzhIaKz2qI1qlh+YGk1tHPfavCXtHzl7mNRv/9F3jVWLjLqBNbV+V9oQqGEZJMaYI8vf6EsZS9PAFe8XcqPSX2AKZSAHEbgQSgPiqUfcSyJ4MG8M5OoRUlQYu3qahVaR78Ha7L/GeAxjbcageobND2cHF/ScZEjMkQf7CSzHhOwAfosnSjKN6+AQBnddD7tnIWGmkleNAuo3d3CRytyImcDRRrUR287OyUWk2XqkxAdwwIi7/8/KOCOYX+1JUT6PlTOoOxLh6Cie8PozbtOZYVTChPsQ1mu2dXUX4TWFEx09y7qNSsHVbz8cxHFMz+meDgNYONZk6HLY8jGmXQ3HAd9RAjjsF3C6slUuULMT2emSvk9PwIbocxJ7oKPiK2VlN/hEbpcsk4JEIJxYVKt25ckSDwq6XjvfWClElPiH/872hITryoxKrn9mIxFYv1/Pw+I4eTocpmt3/Oz7GOhpusQTKeHm9M/ECltWTg7tknnVFS0zd++oAaSTOswe5D/5xOC8rLHX33PbOg6wT+FIZqMcsEkkKb5Hae4vCDE4fmxdFSvYzdxJyyAf//MMwPv/VhVCbsldMD4vJyppRDG0HiSYavX+naosDjkLEf7VH9RVOoBrrGw4E1pzjzRCG8t37rMhcC8AGytMjz6+5gqFETFgeqJlxBBWAA2dFjgc8+AHkCwM+Oekr56h9DDUfvAEME0wMTANBglghkgBZQMEAgEFAAQgBtjaoWzZDzM1Da6nz6y9W1dLd7IwbwatH+MtkRAqwrsEFCevKlvA9rjLeyO0ibHSOt69BQ11AgInEA==
      
      - name: Build
        run: ./gradlew assembleRelease
        env:
          KEYSTORE_FILE: ${{ github.workspace }}/Android/src/gallery-release.keystore
          KEYSTORE_PASSWORD: androidreleasekey
          KEY_ALIAS: androidreleasekey
          KEY_PASSWORD: androidreleasekey
      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: gallery-app-release
          path: Android/src/app/build/outputs/apk/release/app-release.apk