name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'Android/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'Android/**'

jobs:
  build_apk:
    name: Build Android APK
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Android/src
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v3
      
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      
      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_FILE }}" | base64 --decode > gallery-release.keystore
        env:
          KEYSTORE_FILE: MIIKxgIBAzCCCnAGCSqGSIb3DQEHAaCCCmEEggpdMIIKWTCCBbAGCSqGSIb3DQEHAaCCBaEEggWdMIIFmTCCBZUGCyqGSIb3DQEMCgECoIIFQDCCBTwwZgYJKoZIhvcNAQUNMFkwOAYJKoZIhvcNAQUMMCsEFDPzei6CfpyThjD1gI3z805yEgS7AgInEAIBIDAMBggqhkiG9w0CCQUAMB0GCWCGSAFlAwQBKgQQT35UFer2tVhPZeFb7ANcgQSCBNDY4x0LSj1Wmde73U8UFiHmuOrWSHOWUVathsGREUGcMepPtzgligghiql2IFnB8qwN5I+bLdhGpT/hiwfkmhYBSeygpaMUOTRF7kJBu5lY+GCicRAN9LVXSasiRZ+GjnO0M7sxtXpcy9jDPLHipsbpPfExaiaSYoOJaRsrep6hj4w5BSH51CVtT9YEceM8sWe0DjB3B2evM75YOepMBGQPUGZZtT82kyv6ApMs9Wn1gYDkQx0eGf/GAtwKrEq0Kc04XOA3E3sqQ5XHkvSLPTOsM9bms1AcHekcW4iCG8bAfo39AZhf8eLMMYt0YkMMEBxopcCjrddnOl17FFX8Aj2nyS0BI6z2Yyaemxln+MJBIhrJC/+maX3yeTSUoGZzIMXbFGlDzsqGlZCttF10QGIeuufVb5aqxjiPIR9+WeNs6kuBY0WzHkEm0kQNfHpAJfG/zCOtfnGa9x6+L4UUvjSUz3Gr59DeIitqbUGYgGJD8CwxR6++Sn5L+OqYlWljtdhvbm9K+oSCPVpiIIjX2KbGtRSuLsdkYnEe2bVH4jEdfeETpEcSn7/gA7xOU9yjnz8tP+0eZFVxpG2orQxnA2SysBG8D+/UehOtt0rpH6ttTwpiVcSo89QBHl6e++flesTiTgtx36zRdsadV8CTnwlIDg2km/Lc92rEToFS0ukLGvoodecf3+J1JMl/EiMo8AQzweZ2XMSCvdNokP5ZtDgcZTAkrfuR3BTvqLQsCEYsGRjoXtv6bOfSLwFxGCZQEt6CSkS7YWajYRARXx6pABhrJ5QyJZBjxA1ao55LMrhoSo5jbr5J8VjEnNUNgMNAB8i/fYp1M7u/vl4FOlmCKqXkO36Ctw0UX9MtrivDlY1OxaEF4cqBrCTHJMUvHM4dT/ygIuBl9diPFNYaDwwzjZ7jHrwnBajF5fMGlD3/DkmV1fWiM7pBUF83qUM3zexrHztaWAOUUDfzmQoEWO5WWsfUm5Ms1yAEjgInsZk/XcpM6ky/jGG3jYoZhtHqJAYwKLyyBY7PGoAqm+M/S7N140oEwoMm5dKWcp6EJkoR+v82l85vblK/KZVzwqt3k3tIQsXgU/nugBgU/dQGZJ7StIZ3ocYhCha7tbyIx4YNHbvD0YTI6FWhyknNnBGK0iN3YEEx+p+Q1BYpi5B8jnEu/6XJy9M3h6ml1SgqV3WedIuMgHcGpxSBrDA/1tbSCux4r/9HXyKaXKBDf0SwanthOC99xx1u7xAVCAj3QgY94S1e2RxlxnZbHYnsa9JSHBl23j+w+euiQ7SPuMOHJ0uBCfazSuNzeWtAd5Bu+GbUeDCuQp6RfmbPZiuBC8Tj5uNkGrdmbsjgqewj/hY3oU2JiP11uQJZGLs8Q4lBMCxVU0eDtqlAY3reVsEK+2xr31HVyRvz342o0/IO5YbT9ueN2dzWHHKLKCKQUOHXoqQxA000+FpTjP7fAkObz8XvJvHXQ7bLf2mFTIZ+QwHmcuv04Qvh4e/1Z9HQ1TsnoOLSoYVq39ic/3+pkuH9WDrpEc88WAsRXzhe6A3nFFrwU0Jzf9S4AalpEJ9pjN51lWeaDX+Xwd8/TaRY6E2GJzcxunW+VOajYk38ULMTwo61iUSEQEqmBoSnahA9y0THG0crgMZLGTFCMB0GCSqGSIb3DQEJFDEQHg4AZwBhAGwAbABlAHIAeTAhBgkqhkiG9w0BCRUxFAQSVGltZSAxNzc1NDY4NzgxNzQzMIIEoQYJKoZIhvcNAQcGoIIEkjCCBI4CAQAwggSHBgkqhkiG9w0BBwEwZgYJKoZIhvcNAQUNMFkwOAYJKoZIhvcNAQUMMCsEFG7QLZ1xvjkhd/gsaGuE2YbKWCddAgInEAIBIDAMBggqhkiG9w0CCQUAMB0GCWCGSAFlAwQBKgQQexl2nzR1XjICAZqv9aqBnoCCBBBwVtmOR40XeqYukqhzc5HQ07FH2YD4p3IZY/SDExxvQvpSvpS33cz6pj6UIHab5b8qCASzDX1Abt7neEl3G92RvwzpTsqUd9WscHIBQ/4nu/2DGQoditAgdIsgCnuxrNquqzebr+mmpd6mXlujPQAsM9hygiMHsuu3MMVX8aid7DShdPiucoMzrObHOzbfOhnNeDctBSymtbEl+75WAqQeWJBvqsXcBvuylh9tICalgjF/rhS3DxDnX1texyLGI/dZ2NMxkZbhexa71XWfbnzI/5Q7bU7TLcYKwZnvfBYilMIyXy4ReUzMv3JpkHmX1WqZbAeYUN6QPYi5oXj+KODHqZnRQmSqLAGFNmMCtFY1qrsGrLuaRdQq5W1K5czKbaL7li/ir5VDchMGf6fK/fVSArlGxi7d0ten3YAJ5J9zDLbTPIvtzdKqS5JZRC/fzwnGEzA99NeIPqjHfcj5oOahM3cM9XJdVVkEma+QGxoYanZahDJRkEh2Q/vOE/7Uc6s5BQtd7fKED9jgOp1ks4keHLuYswcA91L2lAn6mPGYBdiDpr3VAQcrSc/ryvF4zv7LATs4CY36BUhCtdji4dwVXwKA5KcgJsZPAv0YLmqBLRgjuS3vhCOjYUMuPFDLL8V78gsEWMnvRFJp2GOynFTgzS/NpY/WgWUlGBnOCY2UNuO4OjmyMc/+kvAPkau9mJr7RQ8WctOdIZOakiC9EdGCjxklVq1GWtVTYIk/Ld93DCkR4mXHypN9aZCrLQFxPSiY1OImhf/uQpyY5LDNJbSmmWHQhkzxGaysWNtnTbW2HGRGWPR59F1ffSRym3/9c2ePlsUNA2koQLKushO5OJTRgHmJgHKDPmmPTD5CUWi8OQoldvau/H5DbcLcgL8Vy7LfJiWN354JCPMr81+qnQvsxkBwTb2DoDyju1qJvskjrr9MmKpA3ix32rriCSG4RyxYr/vJIjWJrOAIRteXOhQUvnRuZ69gksqRfmnCpdBBk7BGZK5/XBoci6xyZWqI0CTuTkrbXHFk3Wb5//ZlHxolqxC7ehfh0kFmFrKItG9cPxJhDNcdfhsgZqcyZhcInbOmalEhZbtp+d6C7a7ajRI7JIwabMlowDY9xFfROwt2gl5b5WsG8mfbCJ7it6DtrqV3Rjb5foJ6RlxmXBaotBNiarTj1S8DDoJpaAcDoeFqxyGsledwj0Crbu/4rXa2knUR9TJGrBt1r1DIqvgrUYArtZIdJFDKTeqqOogrUKLLgduuy3Yle2kM4v0JVE0VemQPcbwm+oQzOMclPQYdCch2sP/1YiwX9gEP1gh9tKhl17C6c5cF0mgmJABYGQIEXuQfFCJ12LAoXgEyQqqKnlzlbRDGb1bVmsVjHzshAAhL8jBNMDEwDQYJYIZIAWUDBAIBBQAEINvyrdvzar1mg13eCULdlu+6y+vZ2eOt+SnxMhMh4h7KBBS49nC2dO6B5KZtcRLZG5qgWhCjBAICJxA=
      
      - name: Build
        run: ./gradlew assembleRelease
        env:
          KEYSTORE_FILE: ${{ github.workspace }}/Android/src/gallery-release.keystore
          KEYSTORE_PASSWORD: gallery123
          KEY_ALIAS: gallery
          KEY_PASSWORD: gallery123
      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: gallery-app-release
          path: Android/src/app/build/outputs/apk/release/app-release.apk